"""
Toy sinusoidal + white noise dataset generator.

Signal model:
    s(t) = A * sin(2*pi*f*t + phi)
    x(t) = s(t) + eps(t),   eps(t) ~ N(0, sigma^2)

Generated by Claude (claude-sonnet-4-6).
"""

import numpy as np
from pathlib import Path

# ── Priors ───────────────────────────────────────────────────────────────────
PRIORS = {
    'amplitude':       {'dist': 'uniform', 'low': 0.5,  'high': 1.5},
    'frequency_hz':    {'dist': 'uniform', 'low': 1.0,  'high': 10.0},
    'phase_rad':       {'dist': 'uniform', 'low': 0.0,  'high': 2 * np.pi},
    'noise_amplitude': {'dist': 'normal',  'mean': 5.0, 'std': 1.0},   # clipped > 0
}

# ── Dataset config ────────────────────────────────────────────────────────────
SAMPLE_RATE_HZ  = 64       # Hz
DURATION_S      = 10.0     # seconds  →  640 samples per sequence
N_TOTAL         = 100_000
SPLITS          = {'train': 80_000, 'val': 10_000, 'test': 10_000}
SEED            = 42

# ─────────────────────────────────────────────────────────────────────────────

def generate(n: int, rng: np.random.Generator) -> dict[str, np.ndarray]:
    n_steps = int(DURATION_S * SAMPLE_RATE_HZ)              # 640
    t = (np.arange(n_steps) / SAMPLE_RATE_HZ).astype(np.float32)  # (640,)

    # Sample parameters  (all float32)
    A     = rng.uniform(PRIORS['amplitude']['low'],
                        PRIORS['amplitude']['high'],
                        n).astype(np.float32)
    f     = rng.uniform(PRIORS['frequency_hz']['low'],
                        PRIORS['frequency_hz']['high'],
                        n).astype(np.float32)
    phi   = rng.uniform(PRIORS['phase_rad']['low'],
                        PRIORS['phase_rad']['high'],
                        n).astype(np.float32)
    sigma = rng.normal(PRIORS['noise_amplitude']['mean'],
                       PRIORS['noise_amplitude']['std'],
                       n).astype(np.float32)
    sigma = np.clip(sigma, 1e-3, None)

    # Signals: (n, n_steps)
    phase_grid = 2.0 * np.pi * f[:, None] * t[None, :] + phi[:, None]
    sig     = (A[:, None] * np.sin(phase_grid)).astype(np.float32)
    noise   = (sigma[:, None] * rng.standard_normal((n, n_steps))).astype(np.float32)
    sig_bkg = (sig + noise).astype(np.float32)

    # SNR = RMS(signal) / RMS(noise) = (A / sqrt(2)) / sigma
    snr    = (A / np.sqrt(2.0)) / sigma

    # params: (n, 5)  columns → [amplitude, frequency_hz, phase_rad, noise_amplitude, snr]
    params = np.stack([A, f, phi, sigma, snr], axis=1).astype(np.float32)

    return {'sig': sig, 'sig_bkg': sig_bkg, 'params': params}


def main():
    assert sum(SPLITS.values()) == N_TOTAL, "Split sizes must sum to N_TOTAL"

    rng     = np.random.default_rng(SEED)
    out_dir = Path(__file__).parent

    print(f"Generating {N_TOTAL:,} samples  "
          f"({SAMPLE_RATE_HZ} Hz × {DURATION_S}s = {int(DURATION_S * SAMPLE_RATE_HZ)} steps)")

    data = generate(N_TOTAL, rng)

    cursor = 0
    for split, n in SPLITS.items():
        slices = {key: data[key][cursor:cursor + n] for key in ('sig', 'sig_bkg', 'params')}
        path = out_dir / f'{split}.npz'
        np.savez(path, **slices)
        for key, arr in slices.items():
            print(f'  {split}.npz :: {key}  shape={arr.shape}  dtype={arr.dtype}')
        cursor += n

    print(f"\nSaved to: {out_dir}")


if __name__ == '__main__':
    main()
