"""
Visualize the sinusoidal + white noise toy dataset.

Usage:
    python plot.py [--split train|val|test] [--seed INT] [--data_dir PATH]

Generated by Claude (claude-sonnet-4-6).
"""

import argparse
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

SAMPLE_RATE_HZ = 64
DURATION_S     = 10.0
PARAM_NAMES    = ['amplitude', 'frequency_hz', 'phase_rad', 'noise_amplitude', 'snr']
PARAM_LABELS   = ['Amplitude $A$', 'Frequency $f$ [Hz]', 'Phase $\\phi$ [rad]',
                  'Noise amplitude $\\sigma$', 'SNR']

# ─────────────────────────────────────────────────────────────────────────────

def load_split(data_dir: Path, split: str) -> dict[str, np.ndarray]:
    f = np.load(data_dir / f'{split}.npz')
    return {k: f[k] for k in ('sig', 'sig_bkg', 'params')}


def plot_distributions(params: np.ndarray, out_path: Path) -> None:
    n_params = params.shape[1]
    fig, axes = plt.subplots(1, n_params, figsize=(4 * n_params, 3))
    for ax, label, col in zip(axes, PARAM_LABELS, params.T):
        ax.hist(col, bins=80, color='steelblue', edgecolor='none', alpha=0.85)
        ax.set_xlabel(label)
        ax.set_ylabel('Count')
        ax.ticklabel_format(axis='y', style='sci', scilimits=(0, 0))
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved {out_path}')


def compute_asd(x: np.ndarray, fs: float) -> tuple[np.ndarray, np.ndarray]:
    """One-sided ASD via rfft.  ASD = |FFT| * sqrt(2 / (N * fs))  [units/√Hz]"""
    n   = len(x)
    fft = np.fft.rfft(x)
    asd = np.abs(fft) * np.sqrt(2.0 / (n * fs))
    freqs = np.fft.rfftfreq(n, d=1.0 / fs)
    return freqs, asd


def plot_sample(sig: np.ndarray, sig_bkg: np.ndarray,
                params: np.ndarray, idx: int, out_path: Path) -> None:
    n_steps = sig.shape[1]
    t = np.arange(n_steps) / SAMPLE_RATE_HZ
    A, f, phi, sigma, snr = params[idx]

    fig, (ax_t, ax_f) = plt.subplots(2, 1, figsize=(10, 5))

    # ── Time domain ──────────────────────────────────────────────────────────
    ax_t.plot(t, sig_bkg[idx], color='steelblue', lw=0.8, alpha=0.75, label='signal + noise')
    ax_t.plot(t, sig[idx],     color='tomato',    lw=1.6,              label='signal')
    ax_t.set_xlabel('Time [s]')
    ax_t.set_ylabel('Amplitude')
    ax_t.legend(loc='upper right', fontsize=9, framealpha=0.7)
    ax_t.text(
        0.01, 0.97,
        f'A={A:.3f}  f={f:.2f} Hz  φ={phi:.2f} rad  σ={sigma:.2f}  SNR={snr:.3f}',
        transform=ax_t.transAxes, va='top', fontsize=8, family='monospace',
    )

    # ── ASD ──────────────────────────────────────────────────────────────────
    freqs_bkg, asd_bkg = compute_asd(sig_bkg[idx], SAMPLE_RATE_HZ)
    freqs_sig, asd_sig = compute_asd(sig[idx],     SAMPLE_RATE_HZ)

    ax_f.plot(freqs_bkg, asd_bkg, color='steelblue', lw=0.8, alpha=0.75, label='signal + noise')
    ax_f.plot(freqs_sig, asd_sig, color='tomato',    lw=1.2,              label='signal')
    ax_f.axvline(f, color='tomato', lw=0.8, ls='--', alpha=0.5)
    ax_f.set_xlabel('Frequency [Hz]')
    ax_f.set_ylabel('ASD [1/√Hz]')
    ax_f.set_yscale('log')
    ax_f.legend(loc='upper right', fontsize=9, framealpha=0.7)

    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f'Saved {out_path}')


def main():
    parser = argparse.ArgumentParser(description='Plot toy dataset distributions and a random sample.')
    parser.add_argument('--split',    default='train', choices=['train', 'val', 'test'])
    parser.add_argument('--seed',     type=int, default=0)
    parser.add_argument('--data_dir', default=str(Path(__file__).parent))
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    d = load_split(data_dir, args.split)

    rng = np.random.default_rng(args.seed)
    idx = int(rng.integers(0, len(d['sig'])))
    print(f'Split: {args.split}  |  sample index: {idx}')

    plot_distributions(d['params'], data_dir / 'param_distributions.png')
    plot_sample(d['sig'], d['sig_bkg'], d['params'], idx, data_dir / 'sample.png')


if __name__ == '__main__':
    main()
